website:
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: workshops.qmd
      - href: quickguide.qmd
      - href: faq.qmd
        text: FAQ
      - href: links.qmd
        text: Links
