project:
  type: website
  output-dir: docs

website:
  title: "SWC-JA"
  navbar:
    left: []

format:
  html:
    theme: materia
    css: styles.css
    toc: false

babelquarto:
  languagecodes:
  - name: en
    text: "English"
  - name: ja
    text: "日本語"
  mainlanguage: 'ja'
  languages: ['en']
title-en: SWC-JA
description-en: Software Carpentry Japan
author-en: Joel Nitta
lang: ja
