website:
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: ホーム
      - href: workshops.qmd
      - href: quickguide.qmd
      - href: faq.qmd
      - href: links.qmd
        text: リンク
