project:
  type: website
  output-dir: docs

website:
  title: "SWC-JA"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: ホーム
      - quickguide.qmd
      - links.qmd
      - href: "https://swcarpentry-ja.github.io/en/"
        text: English

format:
  html:
    theme: materia
    css: styles.css
    toc: false
