---
title: よくある質問
toc: true
---

## ワークショップについて

### ワークショップを実施する利点は何ですか？

- カーペントリーズのワークショップは、**研究者によって開発された**、**研究者向け**の内容です。独学では習得が難しい研究に必要なスキルを効率的に学ぶことができます。

- ワークショップの内容は常に更新されています。ソフトウェアのバージョンが更新されて使い方が変わった場合、その変更がレッスン内容に反映されます。そのため、講師（インストラクター）が自ら更新する必要はありません。

- インストラクターは資格を取得することで、教育方法におけるベストプラクティスを身につけています。

- ワークショップを実施したり参加したりすることで、世界各国のメンバーからなるカーペントリーズの広範なコミュニティに参加できます。これにより、ネットワーキングやスキルアップの機会が得られます。

### オフィシャルなワークショップとして認められる条件は何ですか？

オフィシャルなカーペントリーズ・ワークショップとは、[The Carpentries](https://carpentries.org/) の名前やロゴを使用して宣伝されるワークショップを指します。

条件として、カーペントリーズの**資格を持つインストラクター**が**コア・カリキュラム**を教える必要があります。

カーペントリーズのワークショップでは、必ず二人以上のインストラクターが指導しますが、そのうち最低一人は資格を持っている必要があります。ヘルパー（参加者の支援役）の資格は問われず、人数も自由です。

[Software Carpentry のコア・カリキュラム](https://software-carpentry.org/lessons/)には**bashシェル**、**Git**、**R**、または **Python**が含まれています（合計3レッスン）。

### ワークショップの実施にはどのくらいの費用がかかりますか？

多くの方が参加できるよう、ワークショップの参加費は無料または低額に設定されています。

インストラクターはボランティアで活動しているため、謝礼金などは支払われません。

ワークショップの開催にかかる費用（会場費、インストラクターの交通費や宿泊費など）は主催者が負担する必要があります。

教材はクリエイティブ・コモンズ 表示 4.0 国際ライセンスで提供されているため、教材を利用する際のコストは発生しません。

## 参加について

### 誰が対象ですか？

主に研究を行っている方（大学院生、教員、技術スタッフ）が対象です。学部生でも研究活動を行っていれば参加可能です。

[コア・カリキュラム](https://software-carpentry.org/lessons/)（bash シェル、Git、R、または Python）に関する事前知識は不要です（初心者向けです）。

### どうすればインストラクターになれますか？

インストラクターになるには資格が必要です。

資格を取得するには、[講習](https://carpentries.github.io/instructor-training/index.html)（約16時間）を受講する必要があります。講習はオンラインで提供されています。受講を希望する場合は、[こちら](https://amy.carpentries.org/forms/request_training/)から申し込めます。

現在、日本語での講習は準備中です。

## レッスンについて

### 他にどのようなレッスンがありますか？

[オフィシャルなレッスン](https://carpentries.org/lessons/curriculum-summary/)は、Software Carpentry のほかにも提供されています。[Data Carpentry](https://datacarpentry.org/)では、生態学、社会科学、天文学などの分野に特化したデータ解析を教えています。[Library Carpentry](https://librarycarpentry.org/)では、図書館管理に必要なデータ解析スキルを学べます。

また、オフィシャルなレッスン以外にも、コミュニティメンバーが[独自に開発したレッスン](https://carpentries-incubator.org/)も利用できます。

## ザ・カーペントリーズについて

### ソフトウェア・カーペントリーとザ・カーペントリーズの関係は何ですか？

ソフトウェア・カーペントリー（Software Carpentry） は、研究者がプログラミングやデータ管理の基本スキルを学ぶためのワークショップを提供するプロジェクトです。一方、ザ・カーペントリーズ（The Carpentries） は、ソフトウェア・カーペントリーに加えて、データ・カーペントリー（Data Carpentry） や ライブラリー・カーペントリー（Library Carpentry） を統括する組織です。

ザ・カーペントリーズはこれらのプロジェクトを支える役割を果たしており、共通のカリキュラム開発やトレーナーの育成を通じて、カーペントリーズ・コミュニティ全体をサポートしています。

### ソフトウェア・カーペントリー日本はソフトウェア・カーペントリーの翻訳だけをしていますか？

ソフトウェア・カーペントリー日本は、当初ソフトウェア・カーペントリーのカリキュラムの翻訳とワークショップを主な目的として始まりました。しかし、現在ではザ・カーペントリーズ全体のカリキュラムの翻訳やワークショップの実施も視野に入れています。

### ザ・カーペントリーズのビジネスモデルは何ですか？

ザ・カーペントリーズは非営利組織であり、そのビジネスモデルは主に[メンバーシップ料金](https://carpentries.org/support/membership/)、助成金、そして[寄付](https://carpentries.org/support/sponsorship/)によって成り立っています。

主要な支援を提供している財団には、Chan Zuckerberg InitiativeやGordon and Betty Moore Foundationが含まれます。  

メンバーシップは個人向けではなく、研究機関（大学、博物館、図書館など）が年会費を支払うことで特定の特典を得られる仕組みです。この特典には、インストラクターのトレーニングやワークショップの運営支援（インストラクターの派遣など）が含まれます。このように幹部が主催するワークショップは「centrally organized workshop」と呼ばれます。一方で、開催組織が独自にワークショップを企画する場合には、メンバーシップ料金は不要です（「self-hosted workshop」）。  
